apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sitem.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backend.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.backend.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sitem.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mariadb.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mariadb.storage.size }}