apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sitem.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        {{- include "sitem.labels" . | nindent 8 }}
    spec:
      serviceAccountName: sitem-app-sa
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - name: frontend
          image: {{ .Values.image.registry }}/sitem-frontend:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sitem.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80